### ISSUE TITLE
TranslationAPI | Bukket collides with bungee | try if fix possible

### ISSUE THREAD

**Issue by Feier68** [gigaclub/Plugins#38]
```
1.05 19:31:01.132] INFO: [Proxy-1] [19:30:55 WARN]: Exception encountered when loading plugin: BanProxy
[31.05 19:31:01.133] INFO: [Proxy-1] java.lang.NoClassDefFoundError: org/bukkit/plugin/Plugin
[31.05 19:31:01.133] INFO: [Proxy-1]    at net.gigaclub.translation.Translation.<init>(Translation.java:28) ~[?:?]
[31.05 19:31:01.134] INFO: [Proxy-1]    at net.gigaclub.banproxy.BanProxy.onEnable(BanProxy.java:102) ~[?:?]
[31.05 19:31:01.134] INFO: [Proxy-1]    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.135] INFO: [Proxy-1]    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.136] INFO: [Proxy-1]    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.137] INFO: [Proxy-1]    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.137] INFO: [Proxy-1]    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[31.05 19:31:01.138] INFO: [Proxy-1]    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[31.05 19:31:01.138] INFO: [Proxy-1]    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[31.05 19:31:01.139] INFO: [Proxy-1]    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[31.05 19:31:01.139] INFO: [Proxy-1]    at eu.cloudnetservice.wrapper.Wrapper.lambda$startApplication$2(Wrapper.java:246) ~[wrapper.jar:4.0.0-RC8-61a0ada8]
[31.05 19:31:01.140] INFO: [Proxy-1]    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[31.05 19:31:01.140] INFO: [Proxy-1] Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.Plugin
[31.05 19:31:01.141] INFO: [Proxy-1]    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.142] INFO: [Proxy-1]    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
[31.05 19:31:01.142] INFO: [Proxy-1]    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[31.05 19:31:01.143] INFO: [Proxy-1]    ... 12 more
```

**Comment by kevin-fritsch** [comment]
@Feier68 versuchst von bungeecord auf spigot Klasse zuzugreifen
