### ISSUE TITLE
Sometimes a error occurs on reload of a server

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/Plugins#5]
```
[10:20:36 ERROR]: Error occurred while enabling Translation v1.19.0.1.0.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.apache.xmlrpc.client.XmlRpcSun15HttpTransportFactory.getTransport(XmlRpcSun15HttpTransportFactory.java:59) ~[translation-paper-all.jar:?]
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56) ~[translation-paper-all.jar:?]
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167) ~[translation-paper-all.jar:?]
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158) ~[translation-paper-all.jar:?]
	at net.gigaclub.base.odoo.Odoo.setUp(Odoo.java:74) ~[translation-paper-all.jar:?]
	at net.gigaclub.base.odoo.Odoo.<init>(Odoo.java:68) ~[translation-paper-all.jar:?]
	at net.gigaclub.translation.Translation.<init>(Translation.java:30) ~[translation-paper-all.jar:?]
	at net.gigaclub.translation.Main.onEnable(Main.java:51) ~[translation-paper-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-515]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-515]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-515]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-515]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reload(CraftServer.java:1016) ~[paper-1.19.4.jar:git-Paper-515]
	at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-515]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.19.4.jar:git-Paper-515]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.4.jar:git-Paper-515]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.4.jar:git-Paper-515]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-515]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-515]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-515]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.UndeclaredThrowableException: Failed to load resource jar:file:/home/kevin/Development/TestServer/plugins/translation-paper-all.jar!/org/apache/xmlrpc/client/XmlRpcClient.properties: ZipFile invalid LOC header (bad signature)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.<clinit>(XmlRpcHttpTransport.java:84) ~[translation-paper-all.jar:?]
	... 26 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:920) ~[?:?]
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:931) ~[?:?]
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:448) ~[?:?]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:106) ~[?:?]
	at java.util.Properties$LineReader.readLine(Properties.java:503) ~[?:?]
	at java.util.Properties.load0(Properties.java:419) ~[?:?]
	at java.util.Properties.load(Properties.java:408) ~[?:?]
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.<clinit>(XmlRpcHttpTransport.java:76) ~[translation-paper-all.jar:?]
	... 26 more
```

**Comment by Feier68** [comment]
[17.05 23:43:17.890] INFORMATION: [test-1] [23:43:16 ERROR]: Error occurred while enabling BanSystem vunspecified (Is it up to date?)
[17.05 23:43:17.891] INFORMATION: [test-1] java.lang.ExceptionInInitializerError: null
[17.05 23:43:17.892] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcSun15HttpTransportFactory.getTransport(XmlRpcSun15HttpTransportFactory.java:59) ~[BanSystem-all.jar:?]
[17.05 23:43:17.892] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56) ~[BanSystem-all.jar:?]
[17.05 23:43:17.893] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167) ~[BanSystem-all.jar:?]
[17.05 23:43:17.893] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158) ~[BanSystem-all.jar:?]
[17.05 23:43:17.893] INFORMATION: [test-1] at net.gigaclub.base.odoo.Odoo.setUp(Odoo.java:76) ~[BanSystem-all.jar:?]
[17.05 23:43:17.894] INFORMATION: [test-1] at net.gigaclub.base.odoo.Odoo.<init>(Odoo.java:68) ~[BanSystem-all.jar:?]
[17.05 23:43:17.894] INFORMATION: [test-1] at net.gigaclub.translation.Translation.<init>(Translation.java:23) ~[BanSystem-all.jar:?]
[17.05 23:43:17.895] INFORMATION: [test-1] at net.gigaclub.bannsystem.Main.onEnable(Main.java:35) ~[BanSystem-all.jar:?]
[17.05 23:43:17.895] INFORMATION: [test-1] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
[17.05 23:43:17.896] INFORMATION: [test-1] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.896] INFORMATION: [test-1] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.897] INFORMATION: [test-1] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
[17.05 23:43:17.898] INFORMATION: [test-1] at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.899] INFORMATION: [test-1] at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.899] INFORMATION: [test-1] at org.bukkit.craftbukkit.v1_19_R2.CraftServer.reload(CraftServer.java:1022) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.900] INFORMATION: [test-1] at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
[17.05 23:43:17.901] INFORMATION: [test-1] at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
[17.05 23:43:17.901] INFORMATION: [test-1] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
[17.05 23:43:17.902] INFORMATION: [test-1] at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.902] INFORMATION: [test-1] at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.903] INFORMATION: [test-1] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
[17.05 23:43:17.903] INFORMATION: [test-1] at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
[17.05 23:43:17.907] INFORMATION: [test-1] at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
[17.05 23:43:17.907] INFORMATION: [test-1] at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
[17.05 23:43:17.908] INFORMATION: [test-1] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
[17.05 23:43:17.908] INFORMATION: [test-1] at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
[17.05 23:43:17.909] INFORMATION: [test-1] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
[17.05 23:43:17.910] INFORMATION: [test-1] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.910] INFORMATION: [test-1] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[17.05 23:43:17.911] INFORMATION: [test-1] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[17.05 23:43:17.912] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.912] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.913] INFORMATION: [test-1] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[17.05 23:43:17.914] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.914] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.915] INFORMATION: [test-1] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[17.05 23:43:17.915] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.916] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.917] INFORMATION: [test-1] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
[17.05 23:43:17.917] INFORMATION: [test-1] at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17.05 23:43:17.918] INFORMATION: [test-1] Caused by: java.lang.reflect.UndeclaredThrowableException: Failed to load resource jar:file:/C:/Users/Ricardo/Desktop/mc_server/gc_cloudnetserver_test/local/services/test-1/plugins/BanSystem-all.jar!/org/apache/xmlrpc/client/XmlRpcClient.properties: ZipFile invalid LOC header (bad signature)
[17.05 23:43:17.919] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcHttpTransport.<clinit>(XmlRpcHttpTransport.java:84) ~[BanSystem-all.jar:?]
[17.05 23:43:17.922] INFORMATION: [test-1] ... 40 more
[17.05 23:43:17.923] INFORMATION: [test-1] Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
[17.05 23:43:17.923] INFORMATION: [test-1] at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:920) ~[?:?]
[17.05 23:43:17.924] INFORMATION: [test-1] at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:931) ~[?:?]
[17.05 23:43:17.924] INFORMATION: [test-1] at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:448) ~[?:?]
[17.05 23:43:17.925] INFORMATION: [test-1] at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:?]
[17.05 23:43:17.926] INFORMATION: [test-1] at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
[17.05 23:43:17.926] INFORMATION: [test-1] at java.io.FilterInputStream.read(FilterInputStream.java:106) ~[?:?]
[17.05 23:43:17.927] INFORMATION: [test-1] at java.util.Properties$LineReader.readLine(Properties.java:503) ~[?:?]
[17.05 23:43:17.927] INFORMATION: [test-1] at java.util.Properties.load0(Properties.java:419) ~[?:?]
[17.05 23:43:17.928] INFORMATION: [test-1] at java.util.Properties.load(Properties.java:408) ~[?:?]
[17.05 23:43:17.928] INFORMATION: [test-1] at org.apache.xmlrpc.client.XmlRpcHttpTransport.<clinit>(XmlRpcHttpTransport.java:76) ~[BanSystem-all.jar:?]
[17.05 23:43:17.929] INFORMATION: [test-1] ... 40 more
[17.05 23:43:18.979] INFORMATION: [test-1] [23:43:16 INFO]: [BanSystem] Disabling BanSystem vunspecified
